### ISSUE TITLE
Добавить режим игры

### ISSUE THREAD

**Issue by panikajo** [0-BuTaJIuK-0/CSGO-DeathMath-DM#1]
Было-бы не плохо добавить режимы игры по типу бомбы и заложников.

**Comment by 0-BuTaJIuK-0** [comment]
Так это же DM режим (FFA/Каждый сам за себя).
А бомбы и заложники - это все таки командные режимы.
Или я не правильно понял?

Может быть, Вы имели ввиду режим DM и такие под категории:
* Headshot Only
* Only Pistlos
* Only Scout
* и т.д.?
И изменять это прямо во время игры?

**Comment by panikajo** [comment]
Нет я имею ввиду обычные режим бомбы или заложники , в зависимости от карты. Только при этом он ДМ,

**Comment by 0-BuTaJIuK-0** [comment]
Я не представляю, как Вы хотите это реализовать.
Что бы все появлялись так-же по всей карте, стрелялись друг с другом. НО, у кого-то была бомба и он мог её заложить, а другая команда могла разминировать? Если да, то раунд будет заканчиваться? Как в обычном режиме до счета 16?

**Comment by panikajo** [comment]
> Я не представляю, как Вы хотите это реализовать. Что бы все появлялись так-же по всей карте, стрелялись друг с другом. НО, у кого-то была бомба и он мог её заложить, а другая команда могла разминировать? Если да, то раунд будет заканчиваться? Как в обычном режиме до счета 16?

91.200.43.197:27015 вот тут все реализовано

**Comment by 0-BuTaJIuK-0** [comment]
Этот сервер не работает
